from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Info),
admin.site.register(Screening_form),
admin.site.register(randomization),
admin.site.register(Bio_chemical_profile),
admin.site.register(Kuppuswamy_scale),
admin.site.register(weight_monitor),
admin.site.register(Dietary_recall_24hrs),
admin.site.register(Dietary_recall_outcome),
admin.site.register(Patient_Diet_assessment),
admin.site.register(P_sleep_quality_index),
admin.site.register(EPDS),
admin.site.register(daily_Glucose_level_insuline),
admin.site.register(daily_Glucose_level_drug),
admin.site.register(daily_BP),
admin.site.register(Physical_exercise),
admin.site.register(preganacy_delivery),
admin.site.register(Neonatal_outcomes),
admin.site.register(Feedback_forms),
