# Generated by Django 4.1.1 on 2022-09-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drug', models.CharField(default='', max_length=2000)),
                ('Dose', models.CharField(default='', max_length=2000)),
                ('Timings', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='KuppuswamySocioeconomicscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walking_123', models.CharField(choices=[('10', 'Legislators, Senior Officials & Managers'), ('DIPSI', 'NoDIPSI')], max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='biochemical_profile',
            old_name='Acid',
            new_name='ALP',
        ),
        migrations.RenameField(
            model_name='biochemical_profile',
            old_name='Bile',
            new_name='ALT',
        ),
        migrations.RenameField(
            model_name='biochemical_profile',
            old_name='Salts',
            new_name='AST',
        ),
        migrations.RenameField(
            model_name='biochemical_profile',
            old_name='Tripple',
            new_name='A_G_ratio',
        ),
        migrations.RenameField(
            model_name='biochemical_profile',
            old_name='Uric',
            new_name='Albumin',
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Baso',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Baso_Urea',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Bile_Salts',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Bilirubin_I',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Bilirubin_T',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Bilirublin_D',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='CHOL_HDL',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Calcium',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Chloride',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Creatinine',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Eosino',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Eosino_Abs',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Ferritin',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Globulin',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='HDL',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Hb',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Hematocrit',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Iron',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='LDL',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='LDL_HDL',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Lipid_Profile',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Lympho',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Lympho_Abs',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='MCH',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='MCHC',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='MCV',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Mono',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Mono_Abs',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='NRBC',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Neutro',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='NeutroAbsl',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Phosphorus',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Platelet',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Potassium',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='RDW_CV',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Serum_Folate',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Sodium',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='TIBC',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Total_Cholesterol',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Total_protein',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Transferrin',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Triglycerides',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Tripple_Phosphate',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Uric_Acid',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='VLDL',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Vitamin_B12',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='Vitamin_D3',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='Assisted_reproductive_specify',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='alcohol_frequency',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='meditation_frequency',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='physical_frequency',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='smoking_frequency',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='tobacco_frequency',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='walking_frequency',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='maternal_characterstic',
            name='yoga_frequency',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient_demographic',
            name='public_mode_specify',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='Assisted_reproductive_technology',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='F_history_hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='Glucose_test',
            field=models.CharField(choices=[('IADPSG', 'IADPSG'), ('DIPSI', 'NoDIPSI')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='alcohol',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='category',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='chronic_hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='family_history_DM',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='meditation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='nulliparity',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='physical_exercise',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='previous_GDM',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='previous_caesarean_case',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='smoking',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='thrombophilia',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='tobacco',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='walking',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='maternal_characterstic',
            name='yoga',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='Education_level',
            field=models.CharField(choices=[('Diploma', 'Diploma'), ('Graduate', 'Graduate'), ('PostGraduate', 'PostGraduate'), ('Doctorate', 'Doctorate')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='Residence',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='avg_timein_hospital',
            field=models.CharField(choices=[('<30 min', '<30 min'), ('30 to 60 min', '30 to 60 min'), ('1 to 2hr', '1 to 2hr'), (' >2 hr', ' >2 hr')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='family_type',
            field=models.CharField(choices=[('Nuclear', 'Nuclear'), ('Joint', 'Joint')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='mode_of_travel',
            field=models.CharField(choices=[('Private', 'Private'), ('Walk', 'Walk'), ('Public', 'Public'), ('other', 'other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='occuption_status',
            field=models.CharField(choices=[('Working', 'Working'), ('Not-working', 'Not-working')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('other', 'other')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='patient_demographic',
            name='time_to_travel',
            field=models.CharField(choices=[('<30 min', '<30 min'), ('30 to 60 min', '30 to 60 min'), ('1 to 2hr', '1 to 2hr'), (' >2 hr', ' >2 hr')], max_length=1000),
        ),
    ]
