# Generated by Django 4.1.1 on 2022-09-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_current_medication_kuppuswamysocioeconomicscale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diet_outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Glycemic_index', models.TextField()),
                ('Glycemic_load', models.TextField()),
                ('nutri_intake', models.CharField(choices=[('Energy', 'Energy'), ('Protein', 'Protein'), ('CHO', 'CHO'), ('Fat', 'Fat'), ('Fat', 'Fat'), ('Iron', 'Iron'), ('Zinc', 'Zinc'), ('Retinol', 'Retinol'), ('B-Carotene', 'B-Carotene'), ('Thiamin', 'Thiamin'), ('Riboflavin', 'Riboflavin'), ('Niacin', 'Niacin'), ('Vitamin B6', 'Vitamin B6'), ('Riboflavin', 'Riboflavin'), ('Niacin', 'Niacin'), ('Ascorbic acid', 'Ascorbic acid'), ('Dietray folate', 'Dietray folate'), ('Vitamin B12', 'Vitamin B12'), ('Vitamin B6', 'Vitamin B6')], max_length=2000)),
                ('nutri_supplements', models.TextField()),
                ('Multivitimins', models.TextField()),
                ('RDA', models.CharField(default='', max_length=2000)),
                ('actual_intake', models.CharField(default='', max_length=2000)),
                ('Excess_Deficit', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='dietary_recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meal_time', models.DateTimeField(default='', max_length=2000)),
                ('Food_consumed', models.ImageField(default='', null=True, upload_to='images/')),
                ('Quantity', models.DateField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Kuppuswamyscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_family', models.CharField(choices=[('10', 'Legislators, Senior Officials & Managers'), ('9', 'Professionals'), ('8', 'Technicians and Associate Professionals'), ('7', 'Clerks'), ('6', 'Skilled Workers and Shop & Market Sales Workers'), ('5', 'Skilled Agricultural & Fishery Workers'), ('4', 'Craft & Related Trade Workers'), ('3', 'Plant & Machine Operators and Assemblers'), ('2', 'Elementary Occupation'), ('1', 'Unemployed')], max_length=2000)),
                ('education_of_family', models.CharField(choices=[('7', 'Profession or Honours'), ('6', 'Graduate'), ('5', 'Intermediate or diploma'), ('4', 'High school certificate'), ('3', 'Middle school certificate'), ('2', 'Primary school certificate Illiterate'), ('1', 'Illiterate')], max_length=2000)),
                ('income', models.CharField(choices=[('12', '≥ 199,862'), ('10', '99,931–199,861'), ('6', '74,756 –99,930'), ('4', '49,962–74,755'), ('3', '29,973– 49,961'), ('2', '10,002–29,972'), ('1', '≤ 10,001')], max_length=2000)),
                ('economic', models.CharField(choices=[('26-29', 'Upper (I)'), ('16-25', 'Upper Middle (II'), ('11-15', 'Lower Middle (III)'), ('5-10', 'Upper Lower (IV)'), ('<5 Lower', 'Lower (V)')], max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='weight_monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pweight', models.CharField(choices=[('Week 24', 'Week 24'), ('Week 25', 'Week 25'), ('Week 26', 'Week 26'), ('Week 27', 'Week 27'), ('Week 28', 'Week 28'), ('Week 29', 'Week 29'), ('Week 30', 'Week 30'), ('Week 31', 'Week 31'), ('Week 32', 'Week 32'), ('Week 33', 'Week 33'), ('Week 34', 'Week 34'), ('Week 35', 'Week 35'), ('Week 36', 'Week 36'), ('Week 37', 'Week 37')], max_length=2000)),
                ('Weight', models.CharField(default='', max_length=2000)),
                ('Remarks', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='KuppuswamySocioeconomicscale',
        ),
        migrations.AlterField(
            model_name='current_medication',
            name='Dose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='current_medication',
            name='Drug',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='current_medication',
            name='Timings',
            field=models.TextField(),
        ),
    ]
