# Generated by Django 4.1.1 on 2022-09-18 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_diet_outcome_dietary_recall_kuppuswamyscale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietary_assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fchoice', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-vegetarian', 'Non-vegetarian'), ('Ovo-vegetarian', 'Ovo-vegetarian')], max_length=2000)),
                ('meal', models.CharField(choices=[('Early', 'Early'), ('Breakfast', 'Breakfast'), ('Mid-morning', 'Mid-morning'), ('Lunch', 'Lunch'), ('Evening snack', 'Evening snack'), ('Dinner', 'Dinner'), ('Post-dinner', 'Post-dinner')], max_length=2000)),
                ('weekdays', models.CharField(default='', max_length=2000)),
                ('weekends', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='eat_places',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Daily', models.CharField(default='', max_length=2000)),
                ('Frequently', models.CharField(default='', max_length=2000)),
                ('Occasionally', models.CharField(default='', max_length=2000)),
                ('Never', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='EPDS',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('POG', models.CharField(default='', max_length=2000)),
                ('Subj_Code', models.CharField(default='', max_length=2000)),
                ('Ghealth', models.CharField(choices=[('1', 'Excellent'), ('2', 'Professionals'), ('3', 'Good'), ('4', 'Fair'), ('5', 'Poor')], max_length=2000)),
                ('year', models.CharField(choices=[('1', 'Much better now than one year ago'), ('2', 'Graduate'), ('3', 'Somewhat better now than one year ago'), ('4', 'About the same'), ('5', 'Somewhat worse now than one year ago'), ('5', 'Much worse now than one year ago')], max_length=2000)),
                ('q1', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q2', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q3', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q4', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q6', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q7', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q8', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q9', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q10', models.CharField(choices=[('1', 'Yes, Limited a Lot (1)'), ('2', 'Yes, Limited a Little (2)'), ('3', 'No, Not limited at All (3)')], max_length=2000)),
                ('q11', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=2000)),
                ('q12', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=2000)),
                ('q13', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=2000)),
                ('q14', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=2000)),
                ('q15', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=2000)),
                ('q16', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=2000)),
                ('q20', models.CharField(choices=[('1', 'Not at all'), ('2', 'Slightly'), ('3', 'Moderately'), ('4', 'Quite a bit'), ('5', 'Extremely')], max_length=2000)),
                ('Q21', models.CharField(choices=[('1', 'None'), ('2', 'Very mild'), ('3', 'Mild'), ('4', 'Moderate'), ('5', 'Severe'), ('6', 'Very severe')], max_length=2000)),
                ('Q22', models.CharField(choices=[('1', 'Not at all'), ('2', 'A little bit'), ('3', 'Moderately'), ('4', 'Quite a bit'), ('5', 'Extremely')], max_length=2000)),
                ('Q23', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q24', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q25', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q26', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q27', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q28', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q29', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q30', models.CharField(choices=[('1', 'All of the Time'), ('2', 'Most of the Time'), ('3', 'A Good Bit of the Time'), ('4', 'Some of the Time'), ('5', 'A Little of the Time'), ('6', 'None of the Time')], max_length=2000)),
                ('Q31', models.CharField(choices=[('1', 'All of the time'), ('2', 'Most of the time'), ('3', 'Some of the time'), ('4', 'A little of the time'), ('5', 'None of the time')], max_length=2000)),
                ('Q32', models.CharField(choices=[('1', 'Definitely True'), ('2', 'Mostly True'), ('3', 'Do not Know'), ('4', 'Mostly false'), ('5', 'Definitely false')], max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PSQI',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('POG', models.CharField(default='', max_length=2000)),
                ('Subj_Code', models.CharField(default='', max_length=2000)),
                ('Sleep_duration', models.CharField(default='', max_length=2000)),
                ('Timing', models.DateTimeField(default=datetime.timezone)),
                ('Q1', models.CharField(default='', max_length=2000)),
                ('Q2', models.CharField(default='', max_length=2000)),
                ('Q3', models.CharField(default='', max_length=2000)),
                ('Q4', models.CharField(default='', max_length=2000)),
                ('Q5a', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5b', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5c', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5d', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5e', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5f', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5g', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5h', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5i', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q5j', models.CharField(default='', max_length=2000)),
                ('Q6', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q7', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q8', models.CharField(choices=[('No problem at all', 'No problem at all'), ('Only a very slight problem', 'Only a very slight problem'), ('Somewhat of a problem', 'Somewhat of a problem'), ('A very big problem', 'TA very big problem')], max_length=2000)),
                ('Q9', models.CharField(choices=[('Very good', 'Very good'), ('Fairly good', 'Fairly good'), ('Fairly bad', 'Fairly bad'), ('Very bad', 'Very bad')], max_length=2000)),
                ('Q10', models.CharField(choices=[('No bed partner or room mate', 'No bed partner or room mate'), ('Partner/roommate in other room', 'Partner/roommate in other room'), ('Partner in same room but not same bed', 'Partner in same room but not same bed'), ('Partner in same bed', 'Partner in same bed')], max_length=2000)),
                ('Q10a', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q10b', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q10c', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q10d', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q10e', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
                ('Q10f', models.CharField(choices=[('Not during the past month', 'Not during the past month'), ('Less than once a week', 'Less than once a week'), ('Once or twice a week', 'Once or twice a week'), ('Three or more times a week', 'Three or more times a week')], max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='weight_monitor',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pweight', models.CharField(choices=[('Week 24', 'Week 24'), ('Week 25', 'Week 25'), ('Week 26', 'Week 26'), ('Week 27', 'Week 27'), ('Week 28', 'Week 28'), ('Week 29', 'Week 29'), ('Week 30', 'Week 30'), ('Week 31', 'Week 31'), ('Week 32', 'Week 32'), ('Week 33', 'Week 33'), ('Week 34', 'Week 34'), ('Week 35', 'Week 35'), ('Week 36', 'Week 36'), ('Week 37', 'Week 37')], max_length=2000)),
                ('Patient_Weight', models.CharField(default='', max_length=2000)),
                ('Remarks', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='weight_monitoring',
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='RedBC',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='biochemical_profile',
            name='WhiteBC',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='dietary_recall',
            name='Meal_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dietary_recall',
            name='Quantity',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
