# Generated by Django 4.1.1 on 2022-09-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_dietary_assessment_eat_places_epds_psqi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psqi',
            name='Timing',
        ),
        migrations.AlterField(
            model_name='eat_places',
            name='Daily',
            field=models.CharField(choices=[('Street Hawker', 'Street Hawker'), ('Restaurant', 'Restaurant'), ('Food Courts', 'Food Courts'), ('Dhabas', 'Dhabas'), ('Office canteen', 'Office canteen')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='eat_places',
            name='Frequently',
            field=models.CharField(choices=[('Street Hawker', 'Street Hawker'), ('Restaurant', 'Restaurant'), ('Food Courts', 'Food Courts'), ('Dhabas', 'Dhabas'), ('Office canteen', 'Office canteen')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='eat_places',
            name='Never',
            field=models.CharField(choices=[('Street Hawker', 'Street Hawker'), ('Restaurant', 'Restaurant'), ('Food Courts', 'Food Courts'), ('Dhabas', 'Dhabas'), ('Office canteen', 'Office canteen')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='eat_places',
            name='Occasionally',
            field=models.CharField(choices=[('Street Hawker', 'Street Hawker'), ('Restaurant', 'Restaurant'), ('Food Courts', 'Food Courts'), ('Dhabas', 'Dhabas'), ('Office canteen', 'Office canteen')], max_length=2000),
        ),
    ]
