# Generated by Django 4.1.1 on 2022-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_glucose_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_Glucose_level',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('Breakfast', models.CharField(choices=[('Pre', 'Pre'), ('Post', 'Post')], max_length=2000)),
                ('Lunch', models.CharField(choices=[('Pre', 'Pre'), ('Post', 'Post')], max_length=2000)),
                ('Dinner', models.CharField(choices=[('Pre', 'Pre'), ('Post', 'Post')], max_length=2000)),
                ('Glucose', models.CharField(default='', max_length=2000)),
                ('Timing', models.DateTimeField()),
                ('Insuline', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Glucose_level',
        ),
    ]
